// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gnulinuxindia/internet-chowkidar/internal/config"
	"github.com/gnulinuxindia/internet-chowkidar/pkg/db"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InjectDb() (*db.Queries, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	pool, err := db.ProvideDBConn(configConfig)
	if err != nil {
		return nil, err
	}
	queries := db.ProvideQueries(pool)
	return queries, nil
}

// wire.go:

var dbSet = wire.NewSet(db.ProvideQueries, db.ProvideDBConn, config.ProvideConfig)
